/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managementparksystems.trackpersonel;


import java.awt.Color;
import java.util.List;
import java.util.Random;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import managementparksystems.business.concretes.PersonelManager;
import managementparksystems.business.concretes.ToyManager;
import managementparksystems.entities.concretes.Personel;
import managementparksystems.entities.concretes.Toy;




/**
 *
 * @author Volkan
 */
public class trackPersonel extends javax.swing.JFrame {

    /**
     * Creates new form trackPersonel
     */
    public trackPersonel() { 
        setTitle("Personel Takip Sistemi");
        setLayout(null);
        setResizable(false);
        setSize(800, 500);
        setLocationRelativeTo(rootPane);
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        giris = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        uye = new javax.swing.JPanel();
        uyenoLBL = new javax.swing.JLabel();
        tcnoLBL = new javax.swing.JLabel();
        uyenoTXT = new javax.swing.JTextField();
        tcnoTXT = new javax.swing.JTextField();
        uyeBTN1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        uyeList = new javax.swing.JList();
        cikarBTN = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox3 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personel Takip Sistemi");

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(175, 50));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(801, 295));

        giris.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Giriş", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        giris.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Personel bilgileri için tıklayınız.");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea1);

        jLabel5.setText("Son Eklenen Personeller");

        jTextField10.setText("Aranacak Personel Adı Giriniz:");
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField10MousePressed(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton8.setText("Ara");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout girisLayout = new javax.swing.GroupLayout(giris);
        giris.setLayout(girisLayout);
        girisLayout.setHorizontalGroup(
            girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(girisLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)))
                .addContainerGap())
        );
        girisLayout.setVerticalGroup(
            girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girisLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Giris", giris);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personel Listesi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        //bağlantı b= new bağlantı(); List<sınıf> liste = b.kitapListele(); int boyut=liste.size(); String [][] degerler = new String [boyut][3]; for(int i=0;i<boyut;i++){ sınıf s=liste.get(i); degerler[i][0] = s.kitapadiGetir(); degerler[i][1] = s.yazaradiGetir(); degerler[i][2] = s.yilGetir(); } TableModel m = new DefaultTableModel(degerler,new String[]{"Kitap","Yazar","B.Yılı"} );
        PersonelManager mng = new PersonelManager();
        List<Personel> personels = mng.getAll();

        int boyut=personels.size();
        String [][] values = new String [boyut][7];
        for(int i=0;i<boyut;i++){
            Personel s=personels.get(i);
            values[i][0] = s.getFirstName();
            values[i][1] = s.getLastName();
            values[i][2] = s.getTcNo();
            values[i][3] = s.getMemberNo();
            values[i][4] = s.getWorkPosition();
            values[i][5] = s.getYear();
            values[i][6] = s.getSalary();

        }

        TableModel m = new DefaultTableModel(values,new String[]{"Ad","Soyad","TC No","Üye No","Pozisyon","Doğum Yılı","Maaş"}
        );
        jTable1.setModel(m);
        ;
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Personel Listesi", null, jPanel4, "");

        uye.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personel İşlemleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        uyenoLBL.setText("Üye No :");

        tcnoLBL.setText("TC No :");

        uyenoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyenoTXTActionPerformed(evt);
            }
        });

        tcnoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcnoTXTActionPerformed(evt);
            }
        });

        uyeBTN1.setText("Gönder");
        uyeBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeBTN1ActionPerformed(evt);
            }
        });

        uyeList.setVisibleRowCount(10);
        jScrollPane2.setViewportView(uyeList);

        cikarBTN.setText("Çıkar");
        cikarBTN.setEnabled(false);
        cikarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarBTNActionPerformed(evt);
            }
        });

        jComboBox1.setMaximumRowCount(100);
        jComboBox1.setActionCommand("");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jButton1.setText("AL");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ad :");

        jLabel3.setText("Soyad :");

        jButton2.setText("Değiştir");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Personele Ait Oyuncaklar Listesi");

        javax.swing.GroupLayout uyeLayout = new javax.swing.GroupLayout(uye);
        uye.setLayout(uyeLayout);
        uyeLayout.setHorizontalGroup(
            uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uyeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(uyeLayout.createSequentialGroup()
                            .addComponent(jComboBox1, 0, 201, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uyeLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cikarBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGroup(uyeLayout.createSequentialGroup()
                            .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tcnoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uyenoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uyenoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(tcnoTXT))
                            .addGap(18, 18, 18)
                            .addComponent(uyeBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uyeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uyeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        uyeLayout.setVerticalGroup(
            uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uyeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(uyeLayout.createSequentialGroup()
                            .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uyenoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(uyenoTXT))
                            .addGap(28, 28, 28)
                            .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tcnoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tcnoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(uyeBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(uyeLayout.createSequentialGroup()
                        .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uyeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(uyeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cikarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personel Paneli", uye);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "İşlemler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Üye Ekle");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Üye Sil");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("İşlem :");

        jLabel11.setText("TC No :");

        jLabel12.setText("Ad :");

        jLabel13.setText("Soyad :");

        jButton4.setText("Gönder");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton6.setText("Getir");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(57, 57, 57))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Personel Ekle-Sil", jPanel3);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("* Personel Takip Sistemi *");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setMaximumSize(new java.awt.Dimension(614, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(614, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(614, 48));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Durum");
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Personel Listesi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        
        jTextArea1.setText(null);
        PersonelManager mng = new PersonelManager();
        List<Personel> personels = mng.getAll();
        
        int size = personels.size();
        String [] y = new String[size];
        int i = 0;
        if(i==size){
                jLabel14.setText("-----BAŞARISIZ-----");
                jLabel14.setForeground(Color.black);
                jLabel14.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, "Listeleme başarısız", "Uyarı", JOptionPane.ERROR_MESSAGE);
        }else{
               jLabel14.setText("-----BAŞARILI-----");
               
               jLabel14.setForeground(Color.black);
               jLabel14.setBackground(Color.GREEN);
               JOptionPane.showMessageDialog(null, "Başarılı bir şekilde listelendi", "Gayet Güzel", JOptionPane.INFORMATION_MESSAGE);
        }
        while(i!=size){
            Personel s = personels.get(i);
        y[i] = s.getFirstName()+"\t\t\t"+s.getLastName()+"\t\t\t"+s.getMemberNo();
            jTextArea1.append(y[i]+"\n");
            i++;
        }
        
     
        
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jTextField10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MousePressed
        jTextField10.setText(null);
    }//GEN-LAST:event_jTextField10MousePressed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed

    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String srch=jTextField10.getText();
        new SearchPersonel(srch,"firstName").setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     PersonelManager mng = new PersonelManager();
        List<Personel> personels = mng.getAll();
        
        int boyut=personels.size();
        String [][] values = new String [boyut][7];
        for(int i=0;i<boyut;i++){
            Personel s=personels.get(i);
            values[i][0] = s.getFirstName();
            values[i][1] = s.getLastName();
            values[i][2] = s.getTcNo();
            values[i][3] = s.getMemberNo();
            values[i][4] = s.getWorkPosition();
            values[i][5] = s.getYear();
            values[i][6] = s.getSalary();
            
        }
     
  
        TableModel m = new DefaultTableModel(values,new String[]{"Ad","Soyad","TC No","Üye No","Pozisyon","Doğum Yılı","Maaş"}
        );
        jTable1.setModel(m);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void uyenoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyenoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uyenoTXTActionPerformed

    private void tcnoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcnoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcnoTXTActionPerformed

    private void uyeBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeBTN1ActionPerformed
        
        PersonelManager mng1 = new PersonelManager();
        ToyManager mng2 = new ToyManager();
        String[] data1 = new String[2];
        String[] data2 = new String[10];
        data1=mng1.searchMember(uyenoTXT.getText(), tcnoTXT.getText());
        uyeList.setEnabled(true);
        jTextField1.setText(data1[0]);
        jTextField2.setText(data1[1]);
        jButton2.setEnabled(true);
        cikarBTN.setEnabled(true);
        data2 = mng2.getToysForPersonel(uyenoTXT.getText());
        DefaultListModel list = new DefaultListModel();
        int i=0;
        while(i<10){
            list.addElement(data2[i]);
            i++;
        }
        uyeList.setModel(list);
        
    }//GEN-LAST:event_uyeBTN1ActionPerformed

    private void cikarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarBTNActionPerformed

        if((String)uyeList.getSelectedValue() == "")
        uyeList.setEnabled(false);
        else{
            ToyManager mng1 = new ToyManager();
            ToyManager mng2 = new ToyManager();
            String[] data = new String[10];
            int sonuc=mng1.removeToyFromPersonel((String)uyeList.getSelectedValue(), uyenoTXT.getText());
            if(sonuc==1){
                data = mng2.getToysForPersonel(uyenoTXT.getText());
                DefaultListModel list = new DefaultListModel();
                int i=0;
                while(i<10){
                    list.addElement(data[i]);
                    i++;
                }
                uyeList.setModel(list);
            jLabel14.setText("-----BAŞARILI-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Başarılı bir şekilde oyuncak çıkarıldı", "Gayet Güzel", JOptionPane.INFORMATION_MESSAGE);
            }else{
            uyeList.setEnabled(false);
            jLabel14.setText("-----BAŞARISIZ-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.RED);
            JOptionPane.showMessageDialog(this, "Çıkarma işlemi başarısız lütfen daha sonra tekrar deneyiniz...", "Uyarı", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_cikarBTNActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
        jButton1.setEnabled(true);
        ToyManager mng = new ToyManager();
        List <Toy> toys = mng.getEmptyToys();
        int size = toys.size();
        String [] y = new String[size];
        int i = 0;
        while(i!=size){
            Toy s = toys.get(i);
            y[i] = s.getToyName();
            i++;
        }

        ComboBoxModel c = new DefaultComboBoxModel(y);
        jComboBox1.setModel(c);
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ToyManager mng = new ToyManager();
        int sonuc = mng.addToyToPersonel((String)jComboBox1.getSelectedItem(), uyenoTXT.getText());
        if(sonuc==1){
            jLabel14.setText("-----BAŞARILI-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Başarılı bir şekilde oyuncak geri alındı", "Gayet Güzel", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            jLabel14.setText("-----BAŞARISIZ-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.RED);
            JOptionPane.showMessageDialog(this, "Oyuncağı geri alma işlemi başarısız..", "Uyarı", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        PersonelManager mng = new PersonelManager();
        int result=mng.editMember(tcnoTXT.getText(), jTextField1.getText(), jTextField2.getText());
        if(result==1){
            jLabel14.setText("-----BAŞARILI-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Müşteri bilgileri başarılı bir şekilde değiştirildi..", "Gayet Güzel", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            jLabel14.setText("-----BAŞARISIZ-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.RED);
            JOptionPane.showMessageDialog(this, "Müşteri bilgileri değiştirme işlemi başarısız. Lütfen daha sonra tekrar deneyiniz..", "Uyarı", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jButton4.setText("Ekle");
        
        jButton4.setEnabled(true);
            
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField6.setText("");
        if(jRadioButton3.isSelected()){
            jTextField7.setEditable(true);
            jTextField8.setEditable(true);
            jTextField6.setEditable(true);
        }

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        
        jButton4.setText("Sil");
        jButton6.setEnabled(true);
        PersonelManager mng = new PersonelManager();
        List <Personel> list = mng.getAll();
        int size = list.size();
        String [] y = new String[size];
        int i = 0;
        while(i!=size){
            Personel p = list.get(i);
            y[i] = p.getMemberNo();
            i++;
        }
        ComboBoxModel comboboxModel = new DefaultComboBoxModel(y);
        jComboBox3.setModel(comboboxModel);
        
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField6.setText("");
        if(jRadioButton4.isSelected()){
            jTextField7.setEditable(false);
            jTextField8.setEditable(false);
            jTextField6.setEditable(false);
        }

        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        PersonelManager mng = new PersonelManager();
        String memberNo = new String();
        int b=0;
        if(jButton4.getText()== "Ekle"){
            Random rnd = new Random();
            int no;
            no = 1 + rnd.nextInt(1000);
            char[] crs = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','W','Y','X','Z'};
            int no2 = rnd.nextInt(9);
            memberNo = "90"+no2+crs[rnd.nextInt(25)]+Integer.toString(no)+crs[rnd.nextInt(25)];
            b = mng.addNewMember(memberNo,jTextField6.getText(), jTextField7.getText(), jTextField8.getText());
            //jTextArea2.setText("Başarıyla üye oldunuz. Üye numaranız:"+memberNo+"\n Lütfen Üye Numranızı Bir Kenara Not Ediniz. Önemlidir...");
        }
        else if(jButton4.getText() == "Sil"){
            
            b=mng.deleteMemberWithTcNo(jTextField6.getText(), jTextField7.getText(), jTextField8.getText());
        }
        if(b==1){
            jLabel14.setText("-----BAŞARILI-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.GREEN);
            if(jButton4.getText() == "Ekle"){
                
                jTextArea2.setText("Personel Başarıyla eklendi. Üye numaranız: "+memberNo+"\n Lütfen Üye Numaranızı Bir Kenara Not Ediniz. Önemlidir...");
                JOptionPane.showMessageDialog(this, "Personel başarılı bir şekilde eklendi.", "Gayet Güzel", JOptionPane.INFORMATION_MESSAGE);
            }
           
            if(jButton4.getText() == "Sil"){
                
                jTextArea2.setText("`"+jComboBox3.getSelectedItem()+"`"+" Numaralı Personel başarıyla silindi...");
                JOptionPane.showMessageDialog(this, "Personel başarılı bir şekilde silindi..", "Gayet Güzel", JOptionPane.INFORMATION_MESSAGE);
                jComboBox3.getComponents();
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField6.setText("");
            }
        }
        else{
            jLabel14.setText("-----BAŞARISIZ-----");
            jLabel14.setForeground(Color.black);
            jLabel14.setBackground(Color.RED);
            
            if(jButton4.getText() == "Ekle"){
                
                 jTextArea2.setText("Personel ekleme işleminde hata meydana geldi...");
                 JOptionPane.showMessageDialog(this, "Personel ekleme işlemi başarısız. Lütfen daha sonra tekrar tekrar deneyiniz..", "Uyarı", JOptionPane.ERROR_MESSAGE);
               
            }
            if(jButton4.getText() == "Sil"){
               
                 jTextArea2.setText("Personel silme işleminde hata meydana geldi...");
                 JOptionPane.showMessageDialog(this, "Personel silme işlemi başarısız. Lütfen daha sonra tekrar tekrar deneyiniz..", "Uyarı", JOptionPane.ERROR_MESSAGE);  
            }
           
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        PersonelManager mng = new PersonelManager();
        String [] datas = new String[3];
        datas = mng.alternateSearchMember((String)jComboBox3.getSelectedItem());

        jTextField7.setText(datas[0]);
        jTextField8.setText(datas[1]);
        jTextField6.setText(datas[2]);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField6.setEditable(false);
        jButton4.setEnabled(true);
      
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trackPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trackPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trackPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trackPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trackPersonel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cikarBTN;
    private javax.swing.JPanel giris;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel tcnoLBL;
    private javax.swing.JTextField tcnoTXT;
    private javax.swing.JPanel uye;
    private javax.swing.JButton uyeBTN1;
    private javax.swing.JList uyeList;
    private javax.swing.JLabel uyenoLBL;
    private javax.swing.JTextField uyenoTXT;
    // End of variables declaration//GEN-END:variables
}
